name: Trivy Dependency Scanning

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"   # ВАЖНО — Juice Shop требует 22 для libxmljs2!

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm install

      - name: Generate lock file
        run: npm install --package-lock-only

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | \
            sh -s -- -b /usr/local/bin
          trivy --version


      - name: Download HTML template
        run: |
          curl -sL -o html.tpl https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl

      - name: Run Trivy scan (HTML report)
        run: |
          trivy fs . \
            --format template \
            --template ./html.tpl \
            --output trivy-report.html \
            --dependency-tree \
            --scanners vuln,license,secret

      - name: Generate SBOM
        run: |
          trivy fs . --format cyclonedx --output sbom.json

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.html

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json

